### ISSUE TITLE
VM Ubuntu de 8GB déjà espace libre faible

### ISSUE THREAD

**Issue by dinosaadeh** [ISSAE/smb214-2016#15]
Salut,

J'ai installé le suivant: Ubuntu dans un VirtualBox donnant 1GB RAM et 8GB de disque dur. J'ai installé Tomcat, NetBeans, Chrome, GIT.. C'est drôle ça me donne déjà que je n'ai plus tellement de l'espace libre?! Quelqu'un a eu le même problème? Ai-je donné de mauvais paramètres à ma VM? Merci d'avance.

![capture du 2015-11-12 09-39-57](https://cloud.githubusercontent.com/assets/15226199/11113055/096d7b30-8922-11e5-8b4a-d75e937b90fd.png)

**Comment by pascalfares** [comment]
faire du -s *
dans le home directory

**Comment by dinosaadeh** [comment]
j'ai fais ls -s \* et ça m'a donné

12 examples.desktop
 0 tempdino.txt

Bureau:
total 0

Documents:
total 0

Downloads:
total 46200
46200 google-chrome-stable_current_amd64.deb

glassfish-4.1.1:
total 1684
   4 bin
   4 glassfish
   4 javadb
   4 mq
   4 pkg
   4 README.txt
1660 uninstall.sh

Images:
total 0

Modèles:
total 0

Musique:
total 0

netbeans-8.1:
total 2104
   4 apisupport
   4 bin
   4 cnd
   4 cndext
   4 CREDITS.html
   4 dlight
   4 enterprise
   4 ergonomics
   4 etc
   4 extide
   4 groovy
   4 harness
   4 ide
   4 java
   4 javafx
  40 LICENSE.txt
   4 mobility
  48 moduleCluster.properties
   4 nb
  16 netbeans.css
   4 php
   4 platform
   4 profiler
   8 README.html
 244 THIRDPARTYLICENSE.txt
1660 uninstall.sh
   4 webcommon
   4 websvccommon

Public:
total 0

Téléchargements:
total 0

Vidéos:
total 0

**Comment by pascalfares** [comment]
du pas ls....

**Comment by dinosaadeh** [comment]
j'ai pas bien compris! J'ai utilisé une mauvaise commande?

**Comment by pascalfares** [comment]
fait "du -s *"  du calcul la taille

_____
_Il est toujours préférable de trouver une solution que de produire des
excuses_
_Pascal Fares http://www.cofares.net_

Enseignant ISAE - Cnam Liban
Chef du département informatique http://depinfo.isae.edu.lb Cnam Liban

**Comment by dinosaadeh** [comment]
dino@dino-ubuntu-01:~$ du -s \* -h
4,0K    Bureau
4,0K    Documents
4,0K    Downloads
12K examples.desktop
135M    glassfish-4.1.1
4,0K    Images
4,0K    Modèles
4,0K    Musique
651M    netbeans-8.1
4,0K    Public
147M    Téléchargements
4,0K    tempdino.txt
4,0K    Vidéos

Il n'y a rien vraiment!! J'ai alloué 8GO pour le VM.

**Comment by dinosaadeh** [comment]
Je suppose que je doit recréer le VM avec 10GB au lieu que 8.

**Comment by dinosaadeh** [comment]
J'ai installé le système de nouveau avec 10GB et je suppose que ça a résolu le problème.
