### ISSUE TITLE
VM Ubuntu - Avec le temps le launcher freeze tout le système

### ISSUE THREAD

**Issue by dinosaadeh** [ISSAE/smb214-2016#16]
Après avoir résolu le problème de High CPU with compiz (https://askubuntu.com/questions/562640/high-cpu-with-compiz-and-ubuntu-14/562643#562643?newreg=1249142dc14947e5beef514dcfe13bd7)...

Maintenant j'envisage un autre problème.. Avec le temps, si j'utilise le launcher d'ubuntu, le lancement du launcher est si lent et le système devient si lent jusqu'au point que tout le système s'arrête!

Des idées comment résoudre ce problème?

**Comment by dinosaadeh** [comment]
**MAJ:** avec 10GB de disque dur et 1.5GB RAM, la situation est mieux.. Il y a une lenteur.. Je surveillerai le système pour voir si je peux améliorer la performance. Sinon, je fermerai ce ticket.

**Comment by pascalfares** [comment]
Je vous montrerais comment faire des environnemeny de developpement zvec des virtualisation légère comme docker....

une machine virtuelle complète n'est pas optimale pour des systèmes interactifs. Les interface graphique ne sont pas adaptés aux machine virtuelle elle ont besoin en general d'une carte gaphique dédié. Et ceci n"est pas disponible dans une VM.

**Comment by dinosaadeh** [comment]
Pour préparer, voulez vous que je télécharge la version serveur:
http://www.ubuntu.com/server?

**Comment by pascalfares** [comment]
Oui et tester.
On peut aussi de manière beaucoup plus légère utiliser docker

**Comment by dinosaadeh** [comment]
Mr. Pascal, j'ai installé la version serveur qui est plus petite et sans interface graphique. Pour installer une interface graphique légère, j'ai suivi les instruction de cette page http://www.htpcbeginner.com/install-gui-on-ubuntu-server-14-04-gnome/. Je suppose que le package existe surement dans mon fichier iso. Le desktop package est grand (~1.xGB). Je n'arrive pas à installer ce package depuis ce ISO bien que:
- Je suis aller dans le fichier /etc/apt/sources.list et j'ai gardé le cd-rom comme la source unique des packages.
- comme je n'étais pas sûr que apt-get lisait du CD-ROM, j'ai fait sudo apt-cdrom -d=/mnt/cdrom add (http://askubuntu.com/questions/4694/how-to-use-a-iso-image-as-a-cd-rom-repository).. un ls /mnt/cdrom  montre bien le contenue de .iso.

Enfin, pas de succès.. vous aurez quelques recommendations? Merci
