### ISSUE TITLE
Erreur 403

### ISSUE THREAD

**Issue by GhinaD** [ISSAE/smb214-2016#17]
Salut 

Je suis en train de faire ce simple tutorial comme il est désigné dans ce lien https://netbeans.org/kb/docs/web/security-webapps.html#Exercise_0
en utilisant le serveur GlassFish, en web.xml > security>login>basic et en indiquant le role name

mais quand je viens le fonctionner et mettre le username et le password il me donne cet erreur

n'importe quelle idée s'il vous plait

Merci à l'avance

**Comment by dinosaadeh** [comment]
Quel erreur?

**Comment by GhinaD** [comment]
![403error](https://cloud.githubusercontent.com/assets/13506311/11451465/f129e6e8-95cf-11e5-8e44-b997b4758d89.jpg)

**Comment by dinosaadeh** [comment]
1. C'est quoi l'adresse que vous accédez
2. Pour gagner du temps, pourrez vous envoyer ton projet en zip? Si vous
   ne pouvez pas le faire via github, mettez le sur dropbox ou n'importe et
   partagez le lien SVP.

**Comment by dinosaadeh** [comment]
Je suis entrain de faire l'exercice.. Je ne sais pas si vous avez fait l'étape 7 ou 8... Vous dîtes que vous utilisez GlassFish.. Dans ce cas, c'est l'étape numéro 8 que vous devez faire.. Le nom de ton fichier web.xml me donne l'impression que vous avez fait l'étape 7.

**Comment by GhinaD** [comment]
Bonjour

" If you are deploying your application to a GlassFish or WebLogic server, you need to configure the server deployment descriptor to map the security roles defined in web.xml ..... The GlassFish server deployment descriptor is named glassfish-web.xml "

Alors il faut qu'on a les deux fichiers .. non ?

Et ça c'est mon projet sur dropbox:

https://www.dropbox.com/s/ccqtwjlgvhly53n/WebApplicationSecurity.rar?dl=0

**Comment by dinosaadeh** [comment]
je suppose que vous devez avoir un seul fichier de configuration et non pas
deux. Supprimez le web.xml et laissez celui de glassfish.

Personnellement je n'ai pas terminé l'exemple.. Les étapes ne sont pas
consistent, mal organisé et je suppose qu'il manque une étape pour définir
les groupes dans glassfish. Je ne suis pas sûr.

**Comment by dinosaadeh** [comment]
J'ai téléchargé ta solution et ça ouvre normalement. Quelle est la page qui
retourne cette erreur? Quels sont lest username and password?

**Comment by pascalfares** [comment]
je pourrais le faire en cous si vous vouler

**Comment by GhinaD** [comment]
Oui s'il vous plait Mr.Fares ... parce que j'ai identifié un utilisateur dans glassfish>server config> security>realm>file>manage users : user: ghina et password vide ... la page index.jsp ouvre normalement mais quand je met le user et le pass il ne passe jamais à la page correspondant et me donne cette jolie erreur :) et alors si j'essaie de traiter la page d'admin il se bloque et donne toujours cette erreur même si je fais vider la cache..
