### ISSUE TITLE
Login Form example

### ISSUE THREAD

**Issue by balamddine** [ISSAE/smb214-2016#18]
Bonjour Dr.Pascal

Dans l'example du Login form je n'ai pas comprendre cette ligne ' < form action="j_security_check" method="post" > '
comme je sais l'atrribue action du form prendre la page que tu souhaites faire le post 
ici je sais que j_security_check devra ettre la page erreur.jsp , mais ma problem est que j'ai essaiyé de chercher la relation entre j_security_check et la page d'erreur mais je n'ais pas la trouvée .
"< login-config >
        < auth-method>FORM</auth-method>
        < realm-name>Tomcat8</realm-name>
        < form-login-config>
            < form-login-page>/open/login.jsp</form-login-page>
            < form-error-page>/open/error.jsp</form-error-page>
        < /form-login-config>
    < /login-config>"
ici tu a specifier que dans cas d'erreur tu devrai redirecter sur la page d'erreur donc j'ai conclu que "j_security_check" est seulment un label pour erreur.jsp est ce que c'est correct ma conclusion ?

Merci

**Comment by pascalfares** [comment]
C'est le role du container de faire le travail necessaire

http://xxxxxxxxxx/yyyyyyy/page

si page protégé alors appel de login quand login ok le container envoie vers page
