### ISSUE TITLE
bonsoir, je voudrais le thème "Rest Web Service", s'il vous plait.

### ISSUE THREAD

**Issue by malakKays** [ISSAE/smb214-2016#19]

**Comment by pascalfares** [comment]
Ok propose un plan et un minutage...

**Comment by pascalfares** [comment]
Créer aussi un projet github

**Comment by malakKays** [comment]
bonsoir Dr Pascal,
c'est l'adresse de mon projet github: https://github.com/malakKays/SMB214-Malak-KAYS

**Comment by pascalfares** [comment]
submodule added
