### ISSUE TITLE
demande du sujet Soap WebService

### ISSUE THREAD

**Issue by hassanItani** [ISSAE/smb214-2016#22]
Bonjour Docteur,

j'ai choisi le sujet de Soap WebService puisqu'il est en rapport avec le domaine de mon travail( developpeur des sites web en se basant sur la notion du service web soap)

**Comment by pascalfares** [comment]
Donner une problématique un plan et un minutage

**Comment by hassanItani** [comment]
Bonjour Docteur,

En ce qui concerne le plan, je veux parler sur les points suivants:
1- Definition du SOAP
2- Pourquoi utiliser SOAP?
3- Architecture
            i- Comment Construire un message SOAP
            ii- Règles de syntaxe
4- Comment traiter SOAP FAULT ?
5- Quelques différences entre SOAP et REST
6- Avantages et Inconvenients du SOAP
7- client SOAP et serveur SOAP
8- php exemple sur l'interaction du serveur avec le client SOAP

**Comment by pascalfares** [comment]
mettre le plan dans le README de ton github
