### ISSUE TITLE
demande de sujet "Nouveautés de HTML5"

### ISSUE THREAD

**Issue by balamddine** [ISSAE/smb214-2016#23]

**Comment by pascalfares** [comment]
donner objectif plan et minutage

**Comment by balamddine** [comment]
HTML5 web socket pour creer une application du chat ou HTML5 avec sont element canvas pour creer une game en utilisant le third party javascript library Box2d  ??? est bien ?

**Comment by balamddine** [comment]
avec explication du html5 en gros

**Comment by dinosaadeh** [comment]
Pourquoi du chat? :) quand j'ai pensé à choisir ce sujet je pensais à faire
un jeu!!!

**Comment by balamddine** [comment]
Monsieur Pascal ? j'ai proposer deux sujets pour la Nouveautés du html5 et je prefer la creation du chat system en utilisant pure html5 et css3 pour le UI avec javascript et c# come server side code ( pour la realisation du chargement du Media et file )

**Comment by balamddine** [comment]
1- explication general dans la difference entre html4 et html5
2- le web socket dans html5
3- l'element canvas dans html5 et l'amelioration du graphic des sites web en utilisant le canvas
4- un example d'un system chat en utilisant html5 et la library Signal-R et comment cette library implement le web socket pour envoyer et recevoir des notifications
5 - un petit example d'un jeu utilisant le javascript et le Html5 canvas avec un peux de box2d ( en explicant quoi box2d )

En attend de votre reponse 
Merci!!!

**Comment by pascalfares** [comment]
Créer le projet github pour les documents et tutorial

dans le README plan du thème

**Comment by balamddine** [comment]
Mr .Pascal 
s'il vous plaît se référer à ce lien : https://github.com/balamddine/NewHtml5 pour voir le progrés de mon projet et le plan du thème
En attend de votre acceptation pour que je pourais commencer mon travaille
Merci

**Comment by pascalfares** [comment]
submodule added OK
