### ISSUE TITLE
Demande de sujet "HTML5 and Parallax"

### ISSUE THREAD

**Issue by Ibrahimwatfa** [ISSAE/smb214-2016#24]

**Comment by pascalfares** [comment]
C'est quoi parallax?

**Comment by pascalfares** [comment]
créer un projet github

**Comment by Ibrahimwatfa** [comment]
Parallax c'est un nouveau moyen pour rendre plus fluide la navigation du page web et améliorer l'experience utilisateur. Il est utiliser dans la plusieurs des nouveaux sites et dans la plupart des nouveaux "Smartphone Operating System".

Voici le lien a mon projet: https://github.com/Ibrahimwatfa/HTML5-Parallax

**Comment by pascalfares** [comment]
OK plan dans README de ton projet github
