### ISSUE TITLE
Demande de sujet

### ISSUE THREAD

**Issue by RmailyMike** [ISSAE/smb214-2016#25]
Bonsoire Mr.Pascal,

Je voudrais savoir si je peut choisir le sujet "REST Web Services" si s'est possible parce qu'un autre candidat avait choisi  le meme sujet.

En faite mon plan de travail serait le suivant : 

1) L'architecture REST
2) SOAP Versus REST
3) Quand SOAP et quand REST
4) Example techniques de securite REST
5) Les meilleures pratiques REST

En attente de votre confirmation.

Merci,

**Comment by pascalfares** [comment]
Faudrait ajouter un exemple CRUD en REST comme tutorial

**Comment by RmailyMike** [comment]
Ok, c'est bien noté.

Merci.

**Comment by pascalfares** [comment]
Créer un projet github. Puis le poster ici, ce projet contiendra les documents et les exemples

**Comment by RmailyMike** [comment]
Bonjour Docteur,

Voici l'adresse de mon projet github: 

https://github.com/RmailyMike/RESTful-Web-Services

Cordialement.
