### ISSUE TITLE
Demande de sujet "Java Card"

### ISSUE THREAD

**Issue by ElieKassis** [ISSAE/smb214-2016#26]
Bonjours Dr.,

Je voudrais demander de travailler sur le sujet Java Card, si c'est possible.

Je propose le plan suivant:
1.  Présentation, historique, différents types, propriétés, utilisations…
2.  Sécurité, cryptographie
3.  Transaction et atomicité dans les JAVA cards
4.  Exemples de Programmation

Prière de ne pas hésiter modifier supprimer au ajouter au plan.

Merci d'avance.

**Comment by pascalfares** [comment]
Voir si il existe des simulateur de carte

**Comment by pascalfares** [comment]
creer un projet github ==> plan dans README.md
