### ISSUE TITLE
Choix de Sujet "Oracle Berkeley DB"

### ISSUE THREAD

**Issue by ebouhanna** [ISSAE/smb214-2016#27]
Monsieur Fares,
Suite a votre demande de préparer un sujet d'analyse, j'ai l'intention de préparer une présentation et  un tutoriel sur le Sujet "Oracle Berkeley database Java Edition".

La structure du projet sera présenter prochainement .

J'attend votre avis sur le thème choisi.

Merci.

Elie Bou Hanna

**Comment by pascalfares** [comment]
J'attend le plan et le minutage

créer un  projet github

**Comment by ebouhanna** [comment]
Mr. Fares,

Je viens de créer un répertoire GitHub pour mon projet, 
https://github.com/ebouhanna/SMB214-2016-Oracle-Berkeley-DB-JE.git

Je mettrais a jour prochainement le plan et le minutage du projet.

Merci.

Elie Bou Hanna

**Comment by pascalfares** [comment]
J'attend le plan dans README.md

**Comment by ebouhanna** [comment]
Mr. Fares,

Je viens de proposer un plan pour la présentation dans le README.md de mon Répertoire GiTHub .

 Merci.

**Comment by ebouhanna** [comment]
Mr. Fares,
Il parait que vous n’êtes toujours pas connecte a mon répertoire GiTHub de projet, 
Y a t'il un problème ?

Merci.
