### ISSUE TITLE
Choix de Sujet "Cassandra"

### ISSUE THREAD

**Issue by khalilbsaibes** [ISSAE/smb214-2016#28]
Monsieur Fares,
J'ai l'intention de préparer un système de gestion et du poursuit des expéditions en utilisant « Cassandra » avec une interface web.

Merci.

Khalil Georges Bsaibes

**Comment by pascalfares** [comment]
Faire un plan de présentation de casandra, suivi par un tutorial

**Comment by khalilbsaibes** [comment]
Mon plan de présentation de Cassandra:

1- Cassandra intro et satisfaction de Théorème CAP (CDP).
2- Structure CQL et Indexage
3- Data Réplication
4- Le contrôle de concurrence
5- Caching
6- Connection Node, Requête Lecture/Ecriture 

En attente de votre confirmation.
Merci

**Comment by pascalfares** [comment]
1-Créer un projet github
2-C'est quoi le tutorial?

**Comment by khalilbsaibes** [comment]
Monsieur Fares,
Voici l'adresse de mon projet github: https://github.com/khalilbsaibes/cassandra
A propos du tutorial, Pouvez-vous élaborer davantage?

Merci

**Comment by pascalfares** [comment]
submopdule added
