### ISSUE TITLE
Demande du sujet Java Card

### ISSUE THREAD

**Issue by najidagher** [ISSAE/smb214-2016#29]

**Comment by pascalfares** [comment]
Faire un plan / objectif

**Comment by pascalfares** [comment]
Créer un projet github

**Comment by najidagher** [comment]
Mon Projet Java-Card peut etre surveiller sous l'addresse: https://github.com/najidagher/Java-Card.
Je vous informerai du plan/objectif une fois je coordonne avec mon collegue preparant le meme projet.

**Comment by pascalfares** [comment]
submodule added
