### ISSUE TITLE
Demande d'addition au group 

### ISSUE THREAD

**Issue by mohamadMonzer92** [ISSAE/smb214-2016#30]
Bonsoir, 
Salut monsieur Fares.
Veuillez m'ajouter à l'équipe smb 214-2016, en plus du groupe de Google Drive.
Cordialement.

**Comment by pascalfares** [comment]
Faire la demande pour rejoindre le groupe ici :  https://groups.google.com/a/cnamliban.org/forum/#!forum/smb214-2016

Il faut un compte google

**Comment by jinanhamud** [comment]
Bonsoir ,
Mr fares veuillez m'ajouter a l'equipe SMB 214 -2016 .

**Comment by mohamadMonzer92** [comment]
J'ai fais une demande avant de mettre ce commentaire.
Merci.
