### ISSUE TITLE
Demande de sujet "Websocket" 

### ISSUE THREAD

**Issue by ammaroveold** [ISSAE/smb214-2016#31]

**Comment by pascalfares** [comment]
1-Créer un  projet github

2-Proposer un plan et un minutage

3-Quel exemple?

**Comment by pascalfares** [comment]
How are you coffeCode?

Créer un  projet dans github ==> plan dansd README.md

**Comment by ammaroveold** [comment]
voila l' address de mon projet : https://github.com/aliammar7/WebSocket
merci

**Comment by ammaroveold** [comment]
LE fichier "Readme"  Est Modife
voila le lien  https://github.com/aliammar7/WebSocket
