### ISSUE TITLE
TODO pour chaque audteurs

### ISSUE THREAD

**Issue by pascalfares** [ISSAE/smb214-2016#32]
@ISSAE/smb214-2016 

Chaque auditeurs devrait:

1-créer sont propre projet github. Ce projet contiendra les dcuments et les exemples correspondant a votre travail

2-Me faire parvenir l'adresse de votre projet github

**Comment by hassanItani** [comment]
Bonjour Docteur,

Voici l'adresse de mon projet github: https://github.com/hassanItani/SOAP_SMB214-2016.git
