### ISSUE TITLE
demande de rejoindre

### ISSUE THREAD

**Issue by chadydagher** [ISSAE/smb214-2016#33]
cher Monsieur Pascal,
veuillez accepter ma demande pour rejoindre votre classe " Réseaux, système embarqué et système repartis (1)"  et de m ajjouter a votre liste des email pour commence a recevoir des notifications  
mon email est : chady.dagher1982@gmail.com
et  comment on peut avoir accer au sujet

**Comment by pascalfares** [comment]
Invitation au groupe et a la team OK

voir https://drive.google.com/open?id=1mcRyvtvCQmZFOKsRtLkoA8CK9PPO7Ta-U2g8qeylioQ pour les sujets
