### ISSUE TITLE
demande sujet "cassandra"

### ISSUE THREAD

**Issue by skynete10** [ISSAE/smb214-2016#35]
cassandra

**Comment by pascalfares** [comment]
Faire plan et minutagle

créer projet github

**Comment by skynete10** [comment]
salut docteur pascal.
voici mon plan du projet cassandra:

Plan du projet:
1)  Introduction au nosql et bigdata.
2)  Petite histoire sur Cassandra.
3)  Architecture du Cassandra.
4)  modele des donnees dans Cassandra.
5)  Quand utilizer Cassandra?.
6)  Installation java/Cassandra.
7)  Api sur Cassandra.
8)  Cassandra query language(cql).
9)  Replication des donnees dans Cassandra.
10) Interconnection entre les noeud.
11) Petite application sur Cassandra.
12) Conclusion.
