### ISSUE TITLE
Demande de sujet MongoDB

### ISSUE THREAD

**Issue by AJaafar86** [ISSAE/smb214-2016#36]
Bonjour Mr. Fares ,

J’ai l'intention de préparer une présentation sur le thème mongoDB.
Je vais envoyer le plan durant le deux prochains jours. 

Cordialement,
Ali Jaafar

**Comment by AJaafar86** [comment]
voila l' address de mon projet : https://github.com/AJaafar86/MongoDB.

Cordialement,
Ali Jaafar

**Comment by pascalfares** [comment]
En attente du plan dans README.md dans https://github.com/AJaafar86/MongoDB

**Comment by AJaafar86** [comment]
Bonjour,
 veuillez voir le plan de mon projet dans le fichier README.md dans https://github.com/AJaafar86/MongoDB .

désolée pour le retard.

Cordialement,
Ali Jaafar
