### ISSUE TITLE
demande du sujet cassandra

### ISSUE THREAD

**Issue by AIQ-Academy** [ISSAE/smb214-2016#37]

**Comment by pascalfares** [comment]
Faire plan et minutagle

créer le projet github et me le dire

**Comment by hhamia** [comment]
salut Dr pascal 
plan du mon projet cassandra
I.	introduction au no sql 
II.	 origin et concept du cassandra
III.	 principales cararecteristiques
IV.	  Les cas d'utilisation de Cassandra
V.	 Installation et configuration 
VI.	operation sur les keyspac est sur les table dans cassandra
VII.	dewklfwhjoirhgoiwregjglkjreigjeqotiglkjwgjkewoigjwqiohjqiotgj
VIII.	l'indexation dans cassandra 
IX.	 L'accès aux données dans Cassandra
X.	 communication entre les neouds dans cassandra
XI.	example pratique sur cassandra
XII.	conclusion

Voici l'adresse de mon projet github:https://github.com/hhamia/appache-cassandra-project.git

**Comment by AIQ-Academy** [comment]
salut Dr pascal 
plan du mon projet cassandra
I. introduction au no sql 
II. origin et concept du cassandra
III. principales cararecteristiques
IV. Les cas d'utilisation de Cassandra
V. Installation et configuration 
VI. operation sur les keyspace est sur les table dans cassandra
VII. l'indexation dans cassandra 
VIII. L'accès aux données dans Cassandra
IX. communication entre les neouds dans cassandra
X. example pratique sur cassandra
XI. conclusion

Voici l'adresse de mon projet github:https://github.com/hhamia/appache-cassandra-project.git
