### ISSUE TITLE
Demande de sujet: "HTML5-offline-browsing-and-storage"

### ISSUE THREAD

**Issue by mohamadMonzer92** [ISSAE/smb214-2016#38]
Bonjour Monsieur Pascal,
J'ai l'intention de préparer le sujet "HTML5-offline-browsing-and-storage"
vous trouvez le plan de mon projet dans le fichier README.md
voici l'adresse du projet: https://github.com/Houssein001/HTML5-offline-browsing-and-storage
J'attend votre confirmation pour commencer le travail
Merci.

**Comment by pascalfares** [comment]
Ajoute sous-module ok
