### ISSUE TITLE
Demande sujet "TomEE"

### ISSUE THREAD

**Issue by Tarek-Adra** [ISSAE/smb214-2016#39]
Bonsoire Mr.Pascal,

 s’il est possible je préfère de choisir le sujet de TomEE.

En faite mon plan de travail serait le suivant :

1)  C'est quoi TomEE
2) a propos de TomEE ( Historique, Installation )
3) C'est quoi la difference entre Tomcat et TomEE?
4) TomEE servir plusieurs API (numerote)
5) les avantage d'utilisation TomEE
6) Simple Code CRUD on utilisant TomEE
7) Login et l'authentification en utilisant les fonctions définie dans TomEE
8) Comment définir les rôles pour chacun Admin,  User,... etc,  et comment défie/utiliser "privilige escalation". 
9) ouverture a propos de TomEE+

En attente de votre confirmation.

Link : https://github.com/Tarek-Adra/TomEE

Merci,
Tarek Adra

**Comment by pascalfares** [comment]
Ajouté en tant que sous-module OK
