### ISSUE TITLE
Demande du sujet "RFID" 

### ISSUE THREAD

**Issue by adeiry** [ISSAE/smb214-2016#40]
Bonsoir Mr. Pascal,

J'ai l'intention de préparer une présentation sur le sujet RFID.
Le plan sera envoyer prochainement.
En attendant votre acceptation.

cordialement, 
Alaa DAIRY

**Comment by pascalfares** [comment]
Créer un projet github et mettre dans  README.md le plan

**Comment by adeiry** [comment]
Voici le lien de mon projet: https://github.com/adeiry/RFID.git
