### ISSUE TITLE
Demande de sujet Replication,clustering Mysql

### ISSUE THREAD

**Issue by TR-Amir** [ISSAE/smb214-2016#41]
Mr. Pascal,

J'ai l'intention de préparer une présentation sur le sujet Replication,clustering Mysql.
mon plan est:

-brève introduction pour les notions réplication et clustering
-définition de certains mots-clés pour réplication : load balancing, single point of failure,asynchronous replication,....
-types de réplications de MySQL
-exemple pour mysql buit in replication (type master-salve)
-définition de certains mots-clés pour clustering: in memory database,shared nothing system,distributed nodes,...
-définition et propriétés de  MySQL NDB Cluster
-exemple pour mysql NDB Cluster

En attendant votre acceptation,

Amir Tarhini

**Comment by pascalfares** [comment]
Créer le un projet github mettre dans README.md le plan du travail

**Comment by TR-Amir** [comment]
j'ai creer le projet avec un README.md file pour le plan de travaile. https://github.com/TR-Amir/Replication-Clustering-mysql
