### ISSUE TITLE
Demande de sujet "Neo4j"

### ISSUE THREAD

**Issue by ahmadtout** [ISSAE/smb214-2016#42]
Bonjours Mr.Pascal,
J'ai choisie le sujet "Neo4j"

1- qu'est-ce-que Neo4j
2- Pourqoi graph database ?
3- C'est quoi la difference entre Neo4j et autre database ?
4- Neo4j Tutorial (create, remove, ...)
5- Neo4j Admin 
6- Avantage d'utilisation Neo4j
7- neo4j avec java

j'attent votre confirmation.
Ahmad TOUT

URL: https://github.com/ahmadtout/Neo4j

**Comment by pascalfares** [comment]
Added submodule OK
