### ISSUE TITLE
Demande de sujet raspberry pi

### ISSUE THREAD

**Issue by hussein-al-Arab** [ISSAE/smb214-2016#44]

**Comment by pascalfares** [comment]
Plan et créer un projet github

**Comment by hussein-al-Arab** [comment]
Je voudrais vous présenter le plan de mon sujet, en esperant qu'il obtiendra votre satisfaction:
1- Qu'est ce que raspberry pi 2.
2- Structure (  USB, HDMI, RAM, Micro SD, GPIO ...).
3- GPIO (détails).
4- SE ( Raspbian ...).
5- Programation (Scratch - Python).
6- Exemple pratique.
Je vous remercie d' avance, dans l' attente de votre acceptation.
