### ISSUE TITLE
Demande du sujet "wildfly" 

### ISSUE THREAD

**Issue by TahaniKarroum** [ISSAE/smb214-2016#46]
Bonsoir Mr. Pascal,

J'ai l'intention de préparer une présentation sur le sujet wildfly .
Le plan sera envoyer prochainement.
En attendant votre acceptation.

cordialement,
Tahani karroum

**Comment by pascalfares** [comment]
Créer projet github + plan dans README.md

**Comment by TahaniKarroum** [comment]
Voici le lien de mon projet : https://github.com/TahaniKarroum/WILDFLY
