### ISSUE TITLE
Demande du sujet "RFID"

### ISSUE THREAD

**Issue by chadydagher** [ISSAE/smb214-2016#50]
Bonsoir Mr. Pascal,

J'ai l'intention de préparer une présentation sur le sujet "RFID"
 En attendant votre acceptation.

 Cordialement,
 Chady Dagher

**Comment by pascalfares** [comment]
Créer un  projet github et plan dans README

**Comment by chadydagher** [comment]
Dr.Pascal,
Voici le link
https://github.com/chadydagher/PROJET-RFID/blob/master/README.md
