### ISSUE TITLE
Demande du sujet Android

### ISSUE THREAD

**Issue by mmawaki** [ISSAE/smb214-2016#52]
Salut Mr. Pascal,

J'ai envie de choisir le sujet "Android"
Le plan sera envoyer le plus prochain possible
En attendant votre acceptation

cordialement.

**Comment by mmawaki** [comment]
Salut Mr. Pascal

Voici le plan du projet que je veux elaborer
1. Introduction
2. Un peu d'histoire
3. Besoin et problématique
4. Etude du marché
5. Caractréristiques et Architecture
   
   5.1 Pile de logicielle
   5.2 Android el la platforme Java
   5.3 Android Runtime
6. Utilitaires et atelier du developpement
7. Sécurité
8. Implementation
   
   8.1 Cycle de vie d'une application android
   8.2 Un petit exemple
9. Perspective et future

10.Conclusion

Cordialement.

**Comment by pascalfares** [comment]
1- ce n'est pas un bon plan pour une analyse 

2- Choisir un thème technique et le developper.

3- Créer un projet github

**Comment by mmawaki** [comment]
Salut Mr. Pascal
j'espère que le plan ci-dessous sera un acceptable plan, sinon veuillez m'aider pour arriver a un bon plan, merci
1. Introduction
2. Un peu d'histoire
3. Prérequis et préparation de l'environnement du travail
   1. Utilitaires et atelier du developpement (JDK, Android SDK, ADT, AVD, Eclipse)
   2. Installation
4. Configuration
5. Caractréristiques et Architecture
   1. Composants et structure d'un projet
   2. Comment Créer et initialiser un projet
6. Composants de progarmation d'un projet et cycle de vie
   1. Activités
   2. Services
   3. Fournisseurs de contenu
   4. Récepteurs de diffusion
7. Capteurs
8. Emulateur android
9. Conception d'interface graphique (Layouts)
10. Connection au réseau
11. Android et base de données (SQLITE)
12. Tester un projet
    1. Structure de test
    2. Utilitaires de test
    3. JUnit 
13. Publication d'une appliaction
14. Projet open source d'android
15. Conclusion

Lien vers le projet:
https://github.com/mmawaki/Android
