### ISSUE TITLE
introduction sur la programmation des applications mobile (IOS)

### ISSUE THREAD

**Issue by h0s0n** [ISSAE/smb214-2016#57]
Dear Dr.Pascal,
Je vous souhaite d' accepter mon sujet a representer "la programmation des application IOS"
j' utiliserai le langage objective-C
Merci,
Jouyeus Noel et bonne annee
Hassan Yaakoub

**Comment by dinosaadeh** [comment]
Excuse mon intervention, la dernière technologie utilisé pour le
développement iOS n'est pas en utilisant SWIFT
https://developer.apple.com/swift/?

**Comment by h0s0n** [comment]
Oui c' est on utiliseant SWIFT mais ces deux langage son a peu pret proche ,
pas une beaucoup de difference mais objective-C est plus fort que SWIFT mais quand vous utiliser cette derniere vous pouvez programme en SWIFT facilement pendant que l'inverse est un peu plus difficile

**Comment by h0s0n** [comment]
un petit exemple : 
en objective-C:
    [self uneFonctionQuelconque];
puis : implementer la fonction
-(void)uneFonctionQuelconque
{
}
tandis que en SWIFT : 
    self.uneFonctionQuelconque()
puis : implementer la fonction
func uneFonctionQuelconque()
{
}
(Dans SWIFT on peut programmer sans ";" c' est la seul chose que j'ai aime :p )
