### ISSUE TITLE
Titre du projet

### ISSUE THREAD

**Issue by omaralagha** [ISSAE/smb214-2016#60]
Bonjour Mr Pascal

je pense à une présentation sur le sujet " MySQL cluster "
je veux envoyer le plan suite à votre acceptation

Merci à l'avance
omar alagha

**Comment by abedaziz** [comment]
no merci :+1:

**Comment by pascalfares** [comment]
As tu demarrer le travail?

**Comment by omaralagha** [comment]
bonjour,
oui bien sure monsieru pascal ...
indiquer mois le temps du presentation pour finir le projet
merci

Date: Mon, 7 Mar 2016 22:27:46 -0800
