### ISSUE TITLE
examen sbm214

### ISSUE THREAD

**Issue by balamddine** [ISSAE/smb214-2016#61]
Mr Pascale
Vous avez dit qu'il n'aura pas de l'examen en SMB214 mais nous avons vu que la matier est dans la list de l'examen final en lundi 8/2/2016   ???
est ce que pous vouz nous expliquez s'il vous plais

Merci

**Comment by pascalfares** [comment]
Si il y a bien un examens de synthèse en SMB214

_____
_Il est toujours préférable de trouver une solution que de produire des
excuses_
_Pascal Fares http://www.cofares.net_

Enseignant ISAE - Cnam Liban
Chef du département informatique http://depinfo.isae.edu.lb Cnam Liban
