### ISSUE TITLE
Nodejs avec websocket

### ISSUE THREAD

**Issue by balamddine** [ISSAE/smb214-2016#62]
Mr Pascal 

J'ai creer un petit example demontrant l'implementation d'un system de chat avec node.js et html5 websocket est ce que je peux le presenter aprer l'examen ??? 

Merci

**Comment by pascalfares** [comment]
Tu as déjà passé ta présentation, non?

**Comment by balamddine** [comment]
Bonjour Dr.Pascal

oui, mais puisque nous avons parler sur le Node js dans ma presentation,
j'ai vue qu'elle peux etre une presentation attirant, mais je n'ai pas
complete cette presentation car l'examen a prendre place et vous n'avais
pas repondu donc j'ai croiyer que vous v'avez pas l'accepter

Merci !
