### ISSUE TITLE
Demande une date de présentation

### ISSUE THREAD

**Issue by mmawaki** [ISSAE/smb214-2016#64]
Bonsoir Mr Pascal

Veuillez me choisir une date pour présenter mon projet

Le projet se trouve dans le répertoire https://github.com/mmawaki/Android.git

Cordialement.

**Comment by pascalfares** [comment]
Ce soir Mardi 8 Mars 2016 si tu souhaites

**Comment by mmawaki** [comment]
Je souhaite Jeudi  le 10 mars si possible ça me convient beaucoup plus mieux, sinon a quelle heure sera ce soir?

Cordialement.

**Comment by mmawaki** [comment]
Bonjour Mr Pascal
Je suis très désolé de rater la dernière date de présentation.
est ce que je peux faire ma présentation demain le 15 mars?

Cordialement
