### ISSUE TITLE
Voici Mon Projet SMB214

### ISSUE THREAD

**Issue by khalilbsaibes** [ISSAE/smb214-2016#71]
https://github.com/khalilbsaibes/cassandra

**Comment by pascalfares** [comment]
pourquoi pas en reply à mon message?

vérifier que vous êtes listé ici
https://github.com/ISSAE/smb214-2016/tree/master/Auditeurs

_Pascal Fares : pascal.fares@isae.edu.lb
pascal.fares@isae.edu.lb , pascal.fares@lecnam.net
pascal.fares@lecnam.net ; +9613240246_

​_Chef de *_département informatique ISSAE Cnam Liban*
http://www.cnam-liban.fr/genie-informatique/

_Responsable *_système d'information et environnements numériques
http://si.isae.edu.lb/*

Animateur Open Source Lebanese Movement http://www.cofares.net/ :
pfares@cofares.net

2016-06-08 13:03 GMT+03:00 khalilbsaibes notifications@github.com:
